In [14]:
import numpy as np
import pandas as pd
import math

In [15]:
df = pd.read_excel(r'C:\Users\acer\OPTIMISATION_PROJECT\Tags_content.xlsx',na_values=['\t'])
print(df)

    id type  number tag1 tag2 tag3 tag4 tag5 tag6
0    0    V       4   t3   t6   t7   t9  NaN  NaN
1    1    V       4   t1   t5   t7  t10  NaN  NaN
2    2    V       5   t4   t6   t7   t8  t10  NaN
3    3    V       5   t1   t4   t8   t9  t10  NaN
4    4    V       3   t2   t6   t8  NaN  NaN  NaN
5    5    V       4   t1   t5   t7  t10  NaN  NaN
6    6    V       5   t3   t5   t8   t9  t10  NaN
7    7    V       3   t2   t4   t8  NaN  NaN  NaN
8    8    V       5   t4   t6   t7   t8  t10  NaN
9    9    V       4   t1   t8   t9  t10  NaN  NaN
10  10    V       3   t1   t2   t9  NaN  NaN  NaN
11  11    V       3   t4   t8   t9  NaN  NaN  NaN
12  12    V       2   t3   t9  NaN  NaN  NaN  NaN
13  13    V       5   t2   t4   t5   t6  t10  NaN
14  14    V       5   t2   t5   t7   t8   t9  NaN
15  15    V       5   t4   t5   t7   t9  t10  NaN
16  16    V       3   t6   t7   t9  NaN  NaN  NaN
17  17    V       3   t1   t6   t9  NaN  NaN  NaN
18  18    V       3   t4   t5   t9  NaN  NaN  NaN


In [16]:
#df['tags']=df['tag1']+','+df['tag2']+','+df['tag3']+','+df['tag4']+','+df['tag5']+','+df['tag6']+','+df['tag7']+','+df['tag8']+','+df['tag9']+','+df['tag10']+','+df['tag11']+','+df['tag12']+','+df['tag13']+','+df['tag14']
df['tags']=df['tag1']
df = df.fillna(value=0)
#ar=[]

for i in range(0,50):
    for j in range(4,9):
        if df.iat[i,j]!=0:
            df.iat[i,9]=df.iat[i,9]+','+df.iat[i,j]


print(df)
#data_cell_1 = df.iat[0, 1]                     # Using .iat attribute
#print(data_cell_1)

    id type  number tag1 tag2 tag3 tag4 tag5 tag6                tags
0    0    V       4   t3   t6   t7   t9    0    0         t3,t6,t7,t9
1    1    V       4   t1   t5   t7  t10    0    0        t1,t5,t7,t10
2    2    V       5   t4   t6   t7   t8  t10    0     t4,t6,t7,t8,t10
3    3    V       5   t1   t4   t8   t9  t10    0     t1,t4,t8,t9,t10
4    4    V       3   t2   t6   t8    0    0    0            t2,t6,t8
5    5    V       4   t1   t5   t7  t10    0    0        t1,t5,t7,t10
6    6    V       5   t3   t5   t8   t9  t10    0     t3,t5,t8,t9,t10
7    7    V       3   t2   t4   t8    0    0    0            t2,t4,t8
8    8    V       5   t4   t6   t7   t8  t10    0     t4,t6,t7,t8,t10
9    9    V       4   t1   t8   t9  t10    0    0        t1,t8,t9,t10
10  10    V       3   t1   t2   t9    0    0    0            t1,t2,t9
11  11    V       3   t4   t8   t9    0    0    0            t4,t8,t9
12  12    V       2   t3   t9    0    0    0    0               t3,t9
13  13    V       5 

In [17]:
df = df.drop(df.columns[[1,2,3,4,5,6,7,8]], axis=1)

In [18]:
print(df)

    id                tags
0    0         t3,t6,t7,t9
1    1        t1,t5,t7,t10
2    2     t4,t6,t7,t8,t10
3    3     t1,t4,t8,t9,t10
4    4            t2,t6,t8
5    5        t1,t5,t7,t10
6    6     t3,t5,t8,t9,t10
7    7            t2,t4,t8
8    8     t4,t6,t7,t8,t10
9    9        t1,t8,t9,t10
10  10            t1,t2,t9
11  11            t4,t8,t9
12  12               t3,t9
13  13     t2,t4,t5,t6,t10
14  14      t2,t5,t7,t8,t9
15  15     t4,t5,t7,t9,t10
16  16            t6,t7,t9
17  17            t1,t6,t9
18  18            t4,t5,t9
19  19            t2,t4,t9
20  20           t4,t7,t10
21  21               t6,t9
22  22            t1,t5,t9
23  23            t3,t8,t9
24  24         t1,t5,t8,t9
25  25        t1,t4,t7,t10
26  26               t4,t9
27  27        t3,t8,t9,t10
28  28            t6,t7,t9
29  29         t4,t6,t7,t9
30  30         t5,t7,t8,t9
31  31        t4,t5,t8,t10
32  32        t2,t7,t8,t10
33  33           t3,t4,t10
34  34        t5,t6,t9,t10
35  35     t4,t6,t8,t9,t10
3

In [19]:
from sklearn.feature_extraction.text import CountVectorizer   # using CountVectorizer class
cv = CountVectorizer(max_features=10,stop_words='english')  #taking out top 10 common words

In [20]:
vectors = cv.fit_transform(df['tags']).toarray()

In [21]:
print(vectors)

[[0 0 0 1 0 0 1 1 0 1]
 [1 1 0 0 0 1 0 1 0 0]
 [0 1 0 0 1 0 1 1 1 0]
 [1 1 0 0 1 0 0 0 1 1]
 [0 0 1 0 0 0 1 0 1 0]
 [1 1 0 0 0 1 0 1 0 0]
 [0 1 0 1 0 1 0 0 1 1]
 [0 0 1 0 1 0 0 0 1 0]
 [0 1 0 0 1 0 1 1 1 0]
 [1 1 0 0 0 0 0 0 1 1]
 [1 0 1 0 0 0 0 0 0 1]
 [0 0 0 0 1 0 0 0 1 1]
 [0 0 0 1 0 0 0 0 0 1]
 [0 1 1 0 1 1 1 0 0 0]
 [0 0 1 0 0 1 0 1 1 1]
 [0 1 0 0 1 1 0 1 0 1]
 [0 0 0 0 0 0 1 1 0 1]
 [1 0 0 0 0 0 1 0 0 1]
 [0 0 0 0 1 1 0 0 0 1]
 [0 0 1 0 1 0 0 0 0 1]
 [0 1 0 0 1 0 0 1 0 0]
 [0 0 0 0 0 0 1 0 0 1]
 [1 0 0 0 0 1 0 0 0 1]
 [0 0 0 1 0 0 0 0 1 1]
 [1 0 0 0 0 1 0 0 1 1]
 [1 1 0 0 1 0 0 1 0 0]
 [0 0 0 0 1 0 0 0 0 1]
 [0 1 0 1 0 0 0 0 1 1]
 [0 0 0 0 0 0 1 1 0 1]
 [0 0 0 0 1 0 1 1 0 1]
 [0 0 0 0 0 1 0 1 1 1]
 [0 1 0 0 1 1 0 0 1 0]
 [0 1 1 0 0 0 0 1 1 0]
 [0 1 0 1 1 0 0 0 0 0]
 [0 1 0 0 0 1 1 0 0 1]
 [0 1 0 0 1 0 1 0 1 1]
 [0 1 0 0 0 0 1 0 1 1]
 [1 0 0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0 0 1]
 [1 1 0 0 0 0 1 0 0 1]
 [0 1 0 0 0 0 1 0 1 0]
 [0 0 0 0 1 1 0 0 1 0]
 [0 0 0 1 0 1 1 0 0 0]
 [0 0 0 0 0

In [22]:
cv.get_feature_names()

C:\Python310\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['t1', 't10', 't2', 't3', 't4', 't5', 't6', 't7', 't8', 't9']

In [23]:
from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity(vectors)
similarity[0]

array([1.        , 0.25      , 0.4472136 , 0.2236068 , 0.28867513,
       0.25      , 0.4472136 , 0.        , 0.4472136 , 0.25      ,
       0.28867513, 0.28867513, 0.70710678, 0.2236068 , 0.4472136 ,
       0.4472136 , 0.8660254 , 0.57735027, 0.28867513, 0.28867513,
       0.28867513, 0.70710678, 0.28867513, 0.57735027, 0.25      ,
       0.25      , 0.35355339, 0.5       , 0.8660254 , 0.75      ,
       0.5       , 0.        , 0.25      , 0.28867513, 0.5       ,
       0.4472136 , 0.5       , 0.67082039, 0.70710678, 0.5       ,
       0.28867513, 0.        , 0.57735027, 0.35355339, 0.57735027,
       0.40824829, 0.28867513, 0.57735027, 0.5       , 0.4472136 ])

In [24]:
#sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[1:20]

In [25]:
#def recommend(content_no):
    #content_index = df[df['tags'] == tag_title].index[0]  # fetching movie index from movie title
    #distances = similarity[content_no]                      # gives similarity score of given movie with the rest of the movies
    #content_list = sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:10]
    #double_content_list= sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:20]
    
    #print(content_list[0])
    #print(content_list)
    #number_V=0
    #for i in content_list:
     #   print(df.iloc[i[0]].id,df.iloc[i[0]].type)
        #if df.iloc[i[0]].type == 'V':
         #s   number_V=number_V+1;
            
    #if number_V%2 != 0:
    #    if df.iloc[double_content_list[0]]
    #    print(df.iloc[i[0]].type)
    #return

In [26]:
#recommend(0)